package com.portal.audit.entity;

public enum AuditAction {
    USER_CREATED,
    JOB_POSTED,
    JOB_CLOSED,
    APPLICATION_SUBMITTED,
    APPLICATION_STATUS_CHANGED,
    APPLICATION_WITHDRAWN,
    INTERVIEW_SCHEDULED,
    INTERVIEW_CANCELLED,
    USER_STATUS_CHANGED
}
